server:
  port: 80
  servlet:
    encoding:
      charset: utf-8
      force: true
      
spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/hoa?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: asd1234
  servlet:
    multipart:
      enabled: true
      location: c:/workspace/upload/
  profiles:
    include: API-KEY
#  sql:
#    init: 
#      schema-locations:
#      - classpath:db/table.sql
#      data-locations:
#      - classpath:db/data.sql
  
#  h2:
#    console:
#      enabled: true
#  output: 
#    ansi:
#      enabled: always
mybatis:
  mapper-locations:
  - classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.silver.hallofart.repository.model
